CREATE DATABASE IF NOT EXISTS tp2_ejercicio1;
USE tp2_ejercicio1;

CREATE TABLE IF NOT EXISTS rectangulos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    alto DECIMAL(10,2) NOT NULL,
    ancho DECIMAL(10,2) NOT NULL,
    area DECIMAL(10,2) NOT NULL,
    perimetro DECIMAL(10,2) NOT NULL
);

