### obtener todas las tareas
GET http://localhost:3000/tareas

### filtrar tareas completadas
GET http://localhost:3000/tareas?estado=completadas

### filtrar tareas pendientes
GET http://localhost:3000/tareas?estado=pendientes

### crear una tarea pendiente
POST http://localhost:3000/tareas
Content-Type: application/json

{
  "nombre": "Estudiar para el parcial de Programación IV",
  "completada": false
}

### probar unicidad (crear duplicada)
POST http://localhost:3000/tareas
Content-Type: application/json

{
  "nombre": "estudiar para el parcial de programación iv"
}

### obtener tarea por ID
GET http://localhost:3000/tareas/1

### modificar tarea (marcar como completada)
PUT http://localhost:3000/tareas/1
Content-Type: application/json

{
  "nombre": "Estudiar para el parcial de Programación IV",
  "completada": true
}

### eliminar tarea
DELETE http://localhost:3000/tareas/1