### obtener todas las materias
GET http://localhost:3000/materias

### crear una materia nueva
POST http://localhost:3000/materias
Content-Type: application/json

{
  "nombre": "Programación IV"
}

### obtener todas las calificaciones
GET http://localhost:3000/calificaciones

### crear calificación (Éxito)
POST http://localhost:3000/calificaciones
Content-Type: application/json

{
  "alumno": "Bruno Simonelli",
  "materia_id": 1,
  "nota1": 8,
  "nota2": 9,
  "nota3": 10
}

### probar unicidad alumno-materia (Lanza error 400 por duplicado)
POST http://localhost:3000/calificaciones
Content-Type: application/json

{
  "alumno": "bruno simonelli",
  "materia_id": 1,
  "nota1": 7,
  "nota2": 7,
  "nota3": 7
}

### probar nota fuera de escala (Lanza error de validación)
POST http://localhost:3000/calificaciones
Content-Type: application/json

{
  "alumno": "Carlos Pérez",
  "materia_id": 1,
  "nota1": 12,
  "nota2": 8,
  "nota3": 9
}

### obtener calificación por ID
GET http://localhost:3000/calificaciones/1

### modificar calificación
PUT http://localhost:3000/calificaciones/1
Content-Type: application/json

{
  "alumno": "Bruno Simonelli",
  "materia_id": 1,
  "nota1": 9,
  "nota2": 9,
  "nota3": 10
}

### eliminar calificación
DELETE http://localhost:3000/calificaciones/1